kind: pipeline
type: docker
name: deploy-zitadel
steps:
  - name: create-env-file
    image: alpine:latest
    environment:
      UID:
        from_secret: uid
      ZITADEL_IMAGE:
        from_secret: zitadel_image
      ZITADEL_MASTERKEY:
        from_secret: zitadel_masterkey
      ZITADEL_DB_USER:
        from_secret: zitadel_db_user
      ZITADEL_DB_PASSWORD:
        from_secret: zitadel_db_password
      POSTGRES_USER:
        from_secret: postgres_user
      POSTGRES_PASSWORD:
        from_secret: postgres_password
      ZITADEL_DOMAIN:
        from_secret: zitadel_domain
    commands:
      - printenv | grep -E "^(ZITADEL|POSTGRES|UID)_" > .env
  - name: stop-db
    image: docker/compose:1.29.2
    commands:
      - docker-compose --env-file .env -f docker-compose.yml down db
      - docker-compose --env-file .env -f docker-compose.yml rm -f db
      - docker system prune -f
    depends_on:
      - create-env-file
  - name: start-db
    image: docker/compose:1.29.2
    commands:
      - docker-compose --env-file .env -f docker-compose.yml up -d db
    depends_on:
      - stop-db
  - name: stop-init-zitadel
    image: docker/compose:1.29.2
    commands:
      - docker-compose --env-file .env -f docker-compose.yml down zitadel-init
      - docker-compose --env-file .env -f docker-compose.yml rm -f zitadel-init
      - docker system prune -f
    depends_on:
      - start-db
  - name: init-zitadel
    image: docker/compose:1.29.2
    commands:
      - docker-compose --env-file .env -f docker-compose.yml up -d zitadel-init
    depends_on:
      - stop-init-zitadel
  - name: stop-zitadel
    image: docker/compose:1.29.2
    commands:
      - docker-compose --env-file .env -f docker-compose.yml down zitadel
      - docker-compose --env-file .env -f docker-compose.yml rm -f zitadel
      - docker system prune -f
    depends_on:
      - init-zitadel
  - name: deploy-zitadel
    image: docker/compose:1.29.2
    commands:
      - docker-compose --env-file .env -f docker-compose.yml up -d zitadel
    depends_on:
      - stop-zitadel
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
trigger:
  branch:
    - main
