services:
  zitadel-init:
    image: ${ZITADEL_IMAGE:-ghcr.io/zitadel/zitadel:stable}
    user: "${UID:-1000}"
    command: "init --config /zitadel.yaml"
    environment:
      - ZITADEL_EXTERNALDOMAIN=${ZITADEL_EXTERNALDOMAIN}
      - ZITADEL_AUTH_PASSWORD=${ZITADEL_AUTH_PASSWORD}
      - ZITADEL_FIRSTINSTANCE_ORG_NAME=Waugze
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME=admin@waugze.com
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=${ZITADEL_AUTH_PASSWORD}
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED=false
      - ZITADEL_EXTERNALPORT=8088
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_AUTH_REQUEST_CACHE_SIZE=1000
      - ZITADEL_AUTH_AMOUNTOFCACHEDAUTHREQUESTS=1000
      - ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED=true
      - ZITADEL_DATABASE_POSTGRES_HOST=db
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=${ZITADEL_DB_USER}
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=${ZITADEL_DB_PASSWORD}
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=${POSTGRES_USER}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=${POSTGRES_PASSWORD}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
    networks:
      - "zitadel"
    volumes:
      - ./zitadel.yaml:/zitadel.yaml
    depends_on:
      db:
        condition: "service_healthy"
  zitadel:
    image: ${ZITADEL_IMAGE:-ghcr.io/zitadel/zitadel:stable}
    user: "${UID:-1000}"
    command: 'start-from-setup --tlsMode external --init-projections --masterkey "${ZITADEL_MASTERKEY}" --config /zitadel.yaml --steps /zitadel.yaml'
    environment:
      - ZITADEL_EXTERNALDOMAIN=${ZITADEL_EXTERNALDOMAIN}
      - ZITADEL_AUTH_PASSWORD=${ZITADEL_AUTH_PASSWORD}
      - ZITADEL_FIRSTINSTANCE_ORG_NAME=Waugze
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME=admin@waugze.com
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=${ZITADEL_AUTH_PASSWORD}
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED=false
      - ZITADEL_EXTERNALPORT=8088
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_AUTH_REQUEST_CACHE_SIZE=1000
      - ZITADEL_AUTH_AMOUNTOFCACHEDAUTHREQUESTS=1000
      - ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED=true
      - ZITADEL_DATABASE_POSTGRES_HOST=db
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=${ZITADEL_DB_USER}
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=${ZITADEL_DB_PASSWORD}
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=${POSTGRES_USER}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=${POSTGRES_PASSWORD}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
    networks:
      - "zitadel"
    volumes:
      - ./zitadel.yaml:/zitadel.yaml
    ports:
      - "8088:8080"
    depends_on:
      zitadel-init:
        condition: "service_completed_successfully"
      db:
        condition: "service_healthy"
    restart: "unless-stopped"
    # healthcheck:
    #   test: ["CMD", "/app/zitadel", "ready"]
    #   interval: "10s"
    #   timeout: "5s"
    #   retries: 5
    #   start_period: "10s"
  db:
    restart: "unless-stopped"
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 5s
    networks:
      - "zitadel"
    volumes:
      - zitadel_data:/var/lib/postgresql/data
networks:
  zitadel:
volumes:
  zitadel_data:
    driver: local
