services:
  zitadel-init:
    image: ${ZITADEL_IMAGE:-ghcr.io/zitadel/zitadel:stable}
    user: "${UID:-1000}"
    command: "init --config /zitadel.yaml"
    environment:
      - ZITADEL_EXTERNALDOMAIN=auth.waugze.com
      - ZITADEL_EXTERNALPORT=443
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED=true
      - ZITADEL_DATABASE_POSTGRES_HOST=db
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=${ZITADEL_DB_USER}
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=${ZITADEL_DB_PASSWORD}
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=${POSTGRES_USER}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=${POSTGRES_PASSWORD}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
    networks:
      - "zitadel"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      db:
        condition: "service_healthy"
  zitadel:
    image: ${ZITADEL_IMAGE:-ghcr.io/zitadel/zitadel:stable}
    user: "${UID:-1000}"
    command: 'start-from-setup --production --init-projections --masterkey "${ZITADEL_MASTERKEY}" --config /zitadel.yaml'
    environment:
      - ZITADEL_EXTERNALDOMAIN=auth.waugze.com
      - ZITADEL_EXTERNALPORT=443
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED=true
      - ZITADEL_DATABASE_POSTGRES_HOST=db
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=${ZITADEL_DB_USER}
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=${ZITADEL_DB_PASSWORD}
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=${POSTGRES_USER}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=${POSTGRES_PASSWORD}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
    networks:
      - "zitadel"
    ports:
      - "8088:8080"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test: ["CMD", "/app/zitadel", "ready"]
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "10s"
  db:
    restart: "always"
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 5s
    networks:
      - "zitadel"
    volumes:
      - "data:/var/lib/postgresql/data:rw"
networks:
  zitadel:
volumes:
  data:
